### ISSUE TITLE
Building \amazon\demos\renesas\rx65n-cloud-kit-uart-sx-ulpgn\ccrx-e2studio faild

### ISSUE THREAD

**Issue by DarkRabbit19** [renesas-rx/amazon-freertos#26]
**Describe the bug**
Can not build the project from \amazon\demos\renesas\rx65n-cloud-kit-uart-sx-ulpgn\ccrx-e2studio.

get:
[ERROR] No toolchain set or toolchain not integrated.
and 
/usr/bin/sh: ccrx: command not found
make: *** [lib/aws/greengrass/aws_greengrass_discovery.obj] Error 127
make: *** Waiting for unfinished jobs....

**System information**
- RTK5Rx65N0S00000BE "RenesasRX65N Cloud Kit"
- e2 studio v7.7
- Operating System Windows10 Pro
- Version of Amazon FreeRTOS: 1.49
- Project cloud kit Demo
- If your project is a Custom Application, please add the relevant code snippet in the section `Code to reproduce the bug`. 

**Expected behavior**
The project is built successfully after import and able to debug

**Screenshots or console output**
![image](https://user-images.githubusercontent.com/17086421/73750541-aab8f480-475d-11ea-90f7-174f1da50fd4.png)
![image](https://user-images.githubusercontent.com/17086421/73750646-d3d98500-475d-11ea-94e4-940cc11e1bf5.png)

**To reproduce**

1. install Renesas CC-RX compiler v3.01
2. start e2S
3. confirm Renesas CC-RX compiler v3.01 intergration
4. select \amazon\demos\renesas\rx65n-cloud-kit-uart-sx-ulpgn\ccrx-e2studio
5. built

**Additional context**
I also was trying de amazon-freertos-rx65n-cloud-kit-demos side branch, but it not work

Thank you for your time!

**Comment by VanNamDinh** [comment]
Hi DarkRabbit19,

Thank you for reporting this issue.

Please click right mouse on aws_demos, choose properties -> C/C++ Build -> Settings.
On Settings panel, please choose Toolchain tab. Make sure that Renesas CCRX compiler v3.01 is set there.

![image](https://user-images.githubusercontent.com/52021577/73810469-f3ce7e80-4819-11ea-828b-225e7e3cc229.png)

Let me know if it works or if you have more questions.

**Comment by DarkRabbit19** [comment]
Thanks this, dit fix my problem.
