### ISSUE TITLE
amazon-freertos/demos/renesas/rx64m-gr-kaede/gnurx-e2studio cannot be built

### ISSUE THREAD

**Issue by wolverie** [renesas-rx/amazon-freertos#6]
**Describe the bug**
amazon-freertos/demos/renesas/rx64m-gr-kaede/gnurx-e2studio project build is failed at linking step

**To Reproduce**
1. Clone/download the master branch
2. Import amazon-freertos/demos/renesas/rx64m-gr-kaede/gnurx-e2studio into e2 studio v7.0
3. Select the toolchain as "GCC for Renesas RX" v4.8.4
4. Build project
5. Compiling is OK, but linking is failed

**Build console**

> 'Building target: aws_demos.elf'
> 'Invoking Linker'
> rx-elf-gcc -O2 -fdata-sections -Wunused -Wuninitialized -Wall -Wextra -Wmissing-declarations -Wpointer-arith -Wbad-function-cast -Wshadow -Wstrict-prototypes -Wmissing-prototypes -Wno-unused-function -Wno-unused-label -Wno-unused-variable -Wunused-but-set-variable -Wno-main -g2 -Wstack-usage=256 -mcpu=rx64m -misa=v2 -mlittle-endian-data -o "aws_demos.elf"  ./src/smc_gen/r_pincfg/Pin.o  ./src/smc_gen/general/r_cg_hardware_setup.o ./src/smc_gen/general/r_smc_cgc.o ./src/smc_gen/general/r_smc_cgc_user.o ./src/smc_gen/general/r_smc_interrupt.o  ./src/amazon_freertos_common/network_support/onchip_rx_ether/freertos_ip_hook.o  ./src/amazon_freertos_common/compiler_support/gnuc/assert.o ./src/amazon_freertos_common/compiler_support/gnuc/close.o ./src/amazon_freertos_common/compiler_support/gnuc/fprintf.o ./src/amazon_freertos_common/compiler_support/gnuc/lseek.o ./src/amazon_freertos_common/compiler_support/gnuc/read.o ./src/amazon_freertos_common/compiler_support/gnuc/write.o  ./src/amazon_freertos_common/entropy_hardware_poll.o ./src/amazon_freertos_common/freertos_start.o ./src/amazon_freertos_common/serial_term_uart.o  ./src/FIT_setting_files/r_pincfg/r_ether_rx_pinset.o ./src/FIT_setting_files/r_pincfg/r_sci_rx_pinset.o  ./src/FIT_modified_code/r_sci_rx/src/targets/rx64m/r_sci_rx64m.o ./src/FIT_modified_code/r_sci_rx/src/targets/rx64m/r_sci_rx64m_data.o  ./src/FIT_modified_code/r_sci_rx/src/r_sci_rx.o  ./src/FIT_modified_code/r_s12ad_rx/src/targets/rx64m/r_s12ad_rx64m.o  ./src/FIT_modified_code/r_s12ad_rx/src/r_s12ad_rx.o  ./src/FIT_modified_code/r_flash_rx/src/flash_type_4/r_flash_type4.o  ./src/FIT_modified_code/r_flash_rx/src/flash_type_3/r_flash_type3.o  ./src/FIT_modified_code/r_flash_rx/src/flash_type_2/r_flash_type2.o  ./src/FIT_modified_code/r_flash_rx/src/flash_type_1/r_codeflash.o ./src/FIT_modified_code/r_flash_rx/src/flash_type_1/r_codeflash_extra.o ./src/FIT_modified_code/r_flash_rx/src/flash_type_1/r_dataflash.o ./src/FIT_modified_code/r_flash_rx/src/flash_type_1/r_flash_type1.o ./src/FIT_modified_code/r_flash_rx/src/flash_type_1/r_flash_utils.o  ./src/FIT_modified_code/r_flash_rx/src/r_flash_fcu.o ./src/FIT_modified_code/r_flash_rx/src/r_flash_group.o ./src/FIT_modified_code/r_flash_rx/src/r_flash_rx.o  ./src/FIT_modified_code/r_ether_rx/src/targets/rx64m/r_ether_setting_rx64m.o  ./src/FIT_modified_code/r_ether_rx/src/phy/phy.o  ./src/FIT_modified_code/r_ether_rx/src/r_ether_rx.o  ./src/FIT_modified_code/r_byteq/src/r_byteq.o  ./src/FIT_modified_code/r_bsp/mcu/rx64m/cpu.o ./src/FIT_modified_code/r_bsp/mcu/rx64m/locking.o ./src/FIT_modified_code/r_bsp/mcu/rx64m/mcu_clocks.o ./src/FIT_modified_code/r_bsp/mcu/rx64m/mcu_init.o ./src/FIT_modified_code/r_bsp/mcu/rx64m/mcu_interrupts.o ./src/FIT_modified_code/r_bsp/mcu/rx64m/mcu_locks.o ./src/FIT_modified_code/r_bsp/mcu/rx64m/mcu_mapped_interrupts.o ./src/FIT_modified_code/r_bsp/mcu/rx64m/mcu_startup.o  ./src/FIT_modified_code/r_bsp/mcu/all/r_bsp_common.o  ./src/FIT_modified_code/r_bsp/board/rx64m/clkconf.o ./src/FIT_modified_code/r_bsp/board/rx64m/vecttbl.o  ./src/FIT_modified_code/r_bsp/board/generic_rx64m/r_bsp_hwsetup_reference.o  ./src/FIT_modified_code/r_bsp/board/all/dbsct.o ./src/FIT_modified_code/r_bsp/board/all/lowlvl.o ./src/FIT_modified_code/r_bsp/board/all/lowsrc.o ./src/FIT_modified_code/r_bsp/board/all/reset_program.o ./src/FIT_modified_code/r_bsp/board/all/resetprg.o ./src/FIT_modified_code/r_bsp/board/all/sbrk.o  ./lib/third_party/tinycbor/cborencoder.o ./lib/third_party/tinycbor/cborencoder_close_container_checked.o ./lib/third_party/tinycbor/cborerrorstrings.o ./lib/third_party/tinycbor/cborparser.o ./lib/third_party/tinycbor/cborparser_dup_string.o ./lib/third_party/tinycbor/cborpretty.o  ./lib/third_party/mbedtls/source/aes.o ./lib/third_party/mbedtls/source/aesni.o ./lib/third_party/mbedtls/source/arc4.o ./lib/third_party/mbedtls/source/asn1parse.o ./lib/third_party/mbedtls/source/asn1write.o ./lib/third_party/mbedtls/source/base64.o ./lib/third_party/mbedtls/source/bignum.o ./lib/third_party/mbedtls/source/blowfish.o ./lib/third_party/mbedtls/source/camellia.o ./lib/third_party/mbedtls/source/ccm.o ./lib/third_party/mbedtls/source/certs.o ./lib/third_party/mbedtls/source/cipher.o ./lib/third_party/mbedtls/source/cipher_wrap.o ./lib/third_party/mbedtls/source/cmac.o ./lib/third_party/mbedtls/source/ctr_drbg.o ./lib/third_party/mbedtls/source/debug.o ./lib/third_party/mbedtls/source/des.o ./lib/third_party/mbedtls/source/dhm.o ./lib/third_party/mbedtls/source/ecdh.o ./lib/third_party/mbedtls/source/ecdsa.o ./lib/third_party/mbedtls/source/ecjpake.o ./lib/third_party/mbedtls/source/ecp.o ./lib/third_party/mbedtls/source/ecp_curves.o ./lib/third_party/mbedtls/source/entropy.o ./lib/third_party/mbedtls/source/entropy_poll.o ./lib/third_party/mbedtls/source/error.o ./lib/third_party/mbedtls/source/gcm.o ./lib/third_party/mbedtls/source/havege.o ./lib/third_party/mbedtls/source/hmac_drbg.o ./lib/third_party/mbedtls/source/md.o ./lib/third_party/mbedtls/source/md2.o ./lib/third_party/mbedtls/source/md4.o ./lib/third_party/mbedtls/source/md5.o ./lib/third_party/mbedtls/source/md_wrap.o ./lib/third_party/mbedtls/source/memory_buffer_alloc.o ./lib/third_party/mbedtls/source/net_sockets.o ./lib/third_party/mbedtls/source/oid.o ./lib/third_party/mbedtls/source/padlock.o ./lib/third_party/mbedtls/source/pem.o ./lib/third_party/mbedtls/source/pk.o ./lib/third_party/mbedtls/source/pk_wrap.o ./lib/third_party/mbedtls/source/pkcs12.o ./lib/third_party/mbedtls/source/pkcs5.o ./lib/third_party/mbedtls/source/pkparse.o ./lib/third_party/mbedtls/source/pkwrite.o ./lib/third_party/mbedtls/source/platform.o ./lib/third_party/mbedtls/source/platform_util.o ./lib/third_party/mbedtls/source/ripemd160.o ./lib/third_party/mbedtls/source/rsa.o ./lib/third_party/mbedtls/source/rsa_internal.o ./lib/third_party/mbedtls/source/sha1.o ./lib/third_party/mbedtls/source/sha256.o ./lib/third_party/mbedtls/source/sha512.o ./lib/third_party/mbedtls/source/ssl_cache.o ./lib/third_party/mbedtls/source/ssl_ciphersuites.o ./lib/third_party/mbedtls/source/ssl_cli.o ./lib/third_party/mbedtls/source/ssl_cookie.o ./lib/third_party/mbedtls/source/ssl_srv.o ./lib/third_party/mbedtls/source/ssl_ticket.o ./lib/third_party/mbedtls/source/ssl_tls.o ./lib/third_party/mbedtls/source/threading.o ./lib/third_party/mbedtls/source/timing.o ./lib/third_party/mbedtls/source/version.o ./lib/third_party/mbedtls/source/version_features.o ./lib/third_party/mbedtls/source/x509.o ./lib/third_party/mbedtls/source/x509_create.o ./lib/third_party/mbedtls/source/x509_crl.o ./lib/third_party/mbedtls/source/x509_crt.o ./lib/third_party/mbedtls/source/x509_csr.o ./lib/third_party/mbedtls/source/x509write_crt.o ./lib/third_party/mbedtls/source/x509write_csr.o ./lib/third_party/mbedtls/source/xtea.o  ./lib/third_party/jsmn/jsmn.o  ./lib/aws/utils/aws_system_init.o  ./lib/aws/tls/aws_tls.o  ./lib/aws/shadow/aws_shadow.o ./lib/aws/shadow/aws_shadow_json.o  ./lib/aws/secure_sockets/aws_secure_sockets.o  ./lib/aws/pkcs11/aws_pkcs11_mbedtls.o ./lib/aws/pkcs11/aws_pkcs11_pal.o  ./lib/aws/ota/aws_ota_agent.o ./lib/aws/ota/aws_ota_cbor.o ./lib/aws/ota/aws_ota_pal.o  ./lib/aws/mqtt/aws_mqtt_agent.o ./lib/aws/mqtt/aws_mqtt_lib.o  ./lib/aws/greengrass/aws_greengrass_discovery.o ./lib/aws/greengrass/aws_helper_secure_connect.o  ./lib/aws/crypto/aws_crypto.o  ./lib/aws/bufferpool/aws_bufferpool_static_thread_safe.o  ./lib/aws/FreeRTOS/portable/MemMang/heap_4.o  ./lib/aws/FreeRTOS/portable/GCC/RX600v2/port.o  ./lib/aws/FreeRTOS-Plus-TCP/source/portable/NetworkInterface/RX/NetworkInterface.o ./lib/aws/FreeRTOS-Plus-TCP/source/portable/NetworkInterface/RX/ether_callback.o  ./lib/aws/FreeRTOS-Plus-TCP/source/portable/BufferManagement/BufferAllocation_2.o  ./lib/aws/FreeRTOS-Plus-TCP/source/FreeRTOS_ARP.o ./lib/aws/FreeRTOS-Plus-TCP/source/FreeRTOS_DHCP.o ./lib/aws/FreeRTOS-Plus-TCP/source/FreeRTOS_DNS.o ./lib/aws/FreeRTOS-Plus-TCP/source/FreeRTOS_IP.o ./lib/aws/FreeRTOS-Plus-TCP/source/FreeRTOS_Sockets.o ./lib/aws/FreeRTOS-Plus-TCP/source/FreeRTOS_Stream_Buffer.o ./lib/aws/FreeRTOS-Plus-TCP/source/FreeRTOS_TCP_IP.o ./lib/aws/FreeRTOS-Plus-TCP/source/FreeRTOS_TCP_WIN.o ./lib/aws/FreeRTOS-Plus-TCP/source/FreeRTOS_UDP_IP.o  ./lib/aws/FreeRTOS/event_groups.o ./lib/aws/FreeRTOS/list.o ./lib/aws/FreeRTOS/queue.o ./lib/aws/FreeRTOS/stream_buffer.o ./lib/aws/FreeRTOS/tasks.o ./lib/aws/FreeRTOS/timers.o  ./application_code/common_demos/source/aws_demo_runner.o ./application_code/common_demos/source/aws_dev_mode_key_provisioning.o ./application_code/common_demos/source/aws_greengrass_discovery_demo.o ./application_code/common_demos/source/aws_hello_world.o ./application_code/common_demos/source/aws_logging_task_dynamic_buffers.o ./application_code/common_demos/source/aws_ota_update_demo.o ./application_code/common_demos/source/aws_shadow_lightbulb_on_off.o ./application_code/common_demos/source/aws_subscribe_publish_loop.o ./application_code/common_demos/source/aws_tcp_echo_client_separate_tasks.o ./application_code/common_demos/source/aws_tcp_echo_client_single_task.o  ./application_code/main.o    -T "C:/Users/amazon-freertos-master/demos/renesas/rx64m-gr-kaede/gnurx-e2studio/src/linker_script.ld" -Wl,-M=aws_demos.map -Wl,--start-group -lm -lc -lgcc -Wl,--end-group -nostartfiles -Wl,-e_PowerON_Reset_PC
> ./lib/aws/FreeRTOS-Plus-TCP/source/FreeRTOS_DHCP.o: In function `prvInitialiseDHCP':
> C:/Users/amazon-freertos-master/lib/FreeRTOS-Plus-TCP/source/FreeRTOS_DHCP.c:597: undefined reference to `_ulRand'
> ./lib/aws/FreeRTOS-Plus-TCP/source/FreeRTOS_DHCP.o: In function `vDHCPProcess':
> C:/Users/amazon-freertos-master/lib/FreeRTOS-Plus-TCP/source/FreeRTOS_DHCP.c:362: undefined reference to `_ulRand'
> ./lib/aws/FreeRTOS-Plus-TCP/source/FreeRTOS_DNS.o: In function `FreeRTOS_gethostbyname':
> C:/Users/amazon-freertos-master/lib/FreeRTOS-Plus-TCP/source/FreeRTOS_DNS.c:449: undefined reference to `_ulRand'
> ./lib/aws/FreeRTOS-Plus-TCP/source/FreeRTOS_Sockets.o: In function `prvGetPrivatePortNumber':
> C:/Users/amazon-freertos-master/lib/FreeRTOS-Plus-TCP/source/FreeRTOS_Sockets.c:1640: undefined reference to `_ulRand'
> collect2.exe: error: ld returned 1 exit status
> make: *** [aws_demos.elf] Error 1
> makefile:134: recipe for target 'aws_demos.elf' failed
> make: Target 'all' not remade because of errors.
> 
> 10:31:56 Build Failed. 7 errors, 96 warnings. (took 50s.408ms)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - IDE: e2 studio v7.0
 - Compiler: GCC for Renesas RX v4.8.4

**Comment by SheltyDog** [comment]
Thank you very much, I will confirm this issue at this weekend. Please wait.

**Comment by SheltyDog** [comment]
I have updated all projects using Amazon FreeRTOS latest.
please use: f348585383d415c2e931512ad9e6fc2fa09e6bef
